/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/telegram-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coach sign-in with the Telegram Login Widget. */
        post: operations["telegram_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/telegram-webapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mini App sign-in: trades Telegram-signed `initData` for a session token. */
        post: operations["telegram_webapp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/import/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reads an old Telegram plan and matches it against the library. Saves nothing. */
        post: operations["parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check for the hosting platform. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in client's profile. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stores the phone's timezone so reminders arrive at the client's local time. */
        put: operations["set_timezone"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClientProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description IANA timezone reported by the client's phone, e.g. `Europe/Kyiv`. */
            timezone?: string | null;
        };
        ClientSession: {
            client: components["schemas"]["ClientProfile"];
            token: string;
        };
        CoachProfile: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        CoachSession: {
            coach: components["schemas"]["CoachProfile"];
            token: string;
        };
        ErrorBody: {
            /** @description Machine-readable code, e.g. `unauthorized`, `not_a_client`, `unknown_timezone`. */
            error: string;
        };
        Health: {
            database: boolean;
            status: string;
        };
        ImportParseRequest: {
            /** @description An old plan copied from a Telegram message. */
            text: string;
        };
        ImportPreview: {
            exercises: components["schemas"]["ImportedExercise"][];
            /** @description Lines that could not be read, to show the coach. */
            unparsed: string[];
        };
        ImportedExercise: {
            /**
             * Format: uuid
             * @description The library exercise with this name or alias; `null` means it will be added.
             */
            exercise_id?: string | null;
            /** @description The name as written in the plan. */
            name: string;
            note?: string | null;
            per_side_label?: string | null;
            sets: components["schemas"]["ImportedSet"][];
        };
        ImportedSet: {
            /**
             * Format: double
             * @description `null` for bodyweight.
             */
            kg?: number | null;
            /** Format: int32 */
            reps_max: number;
            /** Format: int32 */
            reps_min: number;
        };
        /** @description What the Telegram Login Widget passes to its `data-onauth` callback. */
        LoginWidgetPayload: {
            /** Format: int64 */
            auth_date: number;
            first_name: string;
            hash: string;
            /** Format: int64 */
            id: number;
            last_name?: string | null;
            photo_url?: string | null;
            username?: string | null;
        };
        SetTimezone: {
            /** @description IANA name from `Intl.DateTimeFormat().resolvedOptions().timeZone`. */
            timezone: string;
        };
        WebAppAuthRequest: {
            /** @description `Telegram.WebApp.initData`, exactly as the Mini App received it. */
            init_data: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    telegram_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginWidgetPayload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachSession"];
                };
            };
            /** @description The payload is invalid or older than a day */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `not_a_coach`: this Telegram user is not a coach */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    telegram_webapp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAppAuthRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSession"];
                };
            };
            /** @description `initData` is invalid or older than a day */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `not_a_client`: this Telegram user has no invite */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    parse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportParseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
            /** @description `text_too_long` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `wrong_role` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientProfile"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_timezone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTimezone"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `unknown_timezone` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
