/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/bot-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a coach sign-in that the coach confirms in the bot. */
        post: operations["bot_login_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/bot-login/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collects the result of a coach sign-in started with `/auth/bot-login`. */
        post: operations["bot_login_poll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/telegram-webapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mini App sign-in: trades Telegram-signed `initData` for a session token. */
        post: operations["telegram_webapp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All of the coach's clients, newest first. */
        get: operations["list_clients"];
        put?: never;
        /** Adds a client and returns their first invite link. */
        post: operations["create_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One client. */
        get: operations["get_client"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/clients/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A fresh invite link. The previous unused link stops working.
         * @description For a client who already joined, the new link re-links the profile to whoever
         *     opens it, e.g. after they switched Telegram accounts.
         */
        post: operations["reinvite_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/clients/{id}/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A client's workouts: undated drafts first, then newest date first. */
        get: operations["list_client_workouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The coach's library, alphabetical. Archived exercises are left out. */
        get: operations["list_exercises"];
        put?: never;
        /** Adds an exercise to the library. A video can follow later. */
        post: operations["create_exercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One exercise. While its video is being encoded, this also asks Bunny how far
         *     it got, so the app sees the result even if Bunny's webhook is late.
         */
        get: operations["get_exercise"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Renames, regroups or archives an exercise. */
        patch: operations["update_exercise"];
        trace?: never;
    };
    "/coach/exercises/{id}/video-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Starts a video upload for the exercise: creates the video on Bunny and signs
         *     an upload into it. The current video stays until the new one is encoded.
         */
        post: operations["start_video_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/exercises/{id}/video-uploaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The phone finished uploading; Bunny encodes the video next. */
        post: operations["finish_video_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/import/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reads an old Telegram plan and matches it against the library. Saves nothing. */
        post: operations["parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a workout for a client: blank, or as a copy of an earlier one. */
        post: operations["create_workout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/workouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One workout, for the builder. */
        get: operations["get_workout"];
        /**
         * Saves the whole workout. `If-Match` must carry the version the builder
         *     loaded; if the workout changed since (say, on her laptop), the save is
         *     refused with 409 instead of overwriting.
         */
        put: operations["save_workout"];
        post?: never;
        /** Deletes a workout, published or not. */
        delete: operations["delete_workout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/workouts/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Makes the workout visible to the client and has the bot tell them. Safe to
         *     repeat: the client is told once, e.g. after they join the app.
         */
        post: operations["publish_workout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/workouts/{id}/report/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marks the workout's report as seen, so it stops showing as new. */
        post: operations["mark_report_seen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/workouts/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the client did, set by set next to the plan, and their report. */
        get: operations["get_workout_results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check for the hosting platform. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in client's profile. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stores the phone's timezone so reminders arrive at the client's local time. */
        put: operations["set_timezone"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The client's published and finished workouts, by date. */
        get: operations["list_my_workouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Logs one set. Safe to repeat; a change older than what is stored is ignored,
         *     so sets queued offline cannot undo newer ones.
         */
        put: operations["log_set"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One workout with everything the gym needs: targets, logged results,
         *     Dasha's videos and notes, and last time's numbers.
         */
        get: operations["get_my_workout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workouts/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finishes the workout with a short report, and has the bot tell Dasha.
         *     Sending it again updates the report without messaging her twice.
         */
        post: operations["finish_workout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BotLoginPoll: {
            /** @enum {string} */
            status: "pending";
        } | {
            /** @enum {string} */
            status: "cancelled";
        } | {
            /** @enum {string} */
            status: "expired";
        } | {
            coach: components["schemas"]["CoachProfile"];
            /** @enum {string} */
            status: "approved";
            token: string;
        };
        BotLoginPollRequest: {
            poll_secret: string;
        };
        BotLoginStart: {
            /** @description Opens the bot in Telegram with the login code. */
            bot_url: string;
            /** @description Shown on the page; the bot shows the same digits before the coach confirms. */
            display_code: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Keep in the page; send it to `/auth/bot-login/poll` to collect the token. */
            poll_secret: string;
        };
        ClientExercise: {
            /** Format: uuid */
            id: string;
            /** @description Completed sets from the last earlier workout with this exercise. */
            last_time: components["schemas"]["PastSet"][];
            name: string;
            note?: string | null;
            per_side_label?: string | null;
            sets: components["schemas"]["ClientSet"][];
            video?: components["schemas"]["ClientVideo"] | null;
        };
        ClientProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description IANA timezone reported by the client's phone, e.g. `Europe/Kyiv`. */
            timezone?: string | null;
        };
        ClientSet: {
            /**
             * Format: double
             * @description What the client logged.
             */
            actual_kg?: number | null;
            /** Format: int32 */
            actual_reps?: number | null;
            /**
             * Format: date-time
             * @description The phone's time of the latest logged change, for offline merging.
             */
            client_updated_at?: string | null;
            completed: boolean;
            /** Format: uuid */
            id: string;
            /**
             * Format: double
             * @description Dasha's target; `null` kg is bodyweight.
             */
            target_kg?: number | null;
            /** Format: int32 */
            target_reps_max: number;
            /** Format: int32 */
            target_reps_min: number;
        };
        ClientVideo: {
            hls_url: string;
            /** Format: int32 */
            length_secs?: number | null;
            thumbnail_url: string;
        };
        ClientWorkout: {
            /** Format: date */
            date: string;
            exercises: components["schemas"]["ClientExercise"][];
            /** Format: uuid */
            id: string;
            report?: components["schemas"]["Report"] | null;
            status: components["schemas"]["WorkoutStatus"];
            title: string;
        };
        ClientWorkoutSummary: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            done_set_count: number;
            /** Format: int64 */
            exercise_count: number;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            set_count: number;
            status: components["schemas"]["WorkoutStatus"];
            /** @description The first exercise's video thumbnail, for the card. */
            thumbnail_url?: string | null;
            title: string;
        };
        CoachClient: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description Set while an unused invite exists; it may already have expired.
             */
            invite_expires_at?: string | null;
            /** @description The client opened their invite and is linked to a Telegram account. */
            joined: boolean;
            name: string;
            /** Format: date */
            paid_until?: string | null;
            /**
             * Format: int64
             * @description Reports Dasha has not opened yet.
             */
            unseen_reports: number;
        };
        CoachProfile: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        CoachReport: {
            comment: string;
            /** Format: int32 */
            duration_min?: number | null;
            effort: components["schemas"]["Effort"];
            /** Format: date-time */
            finished_at: string;
            seen: boolean;
        };
        CreatedClient: {
            client: components["schemas"]["CoachClient"];
            invite: components["schemas"]["InviteLink"];
        };
        /** @enum {string} */
        Effort: "easy" | "ok" | "hard";
        ErrorBody: {
            /** @description Machine-readable code, e.g. `unauthorized`, `not_invited`, `unknown_timezone`. */
            error: string;
        };
        Exercise: {
            /** @description Other spellings, used to match imported Telegram plans. */
            aliases: string[];
            /** Format: uuid */
            id: string;
            /** @description Free text; the app offers a fixed set (Спина, Ноги, …). */
            muscle_group?: string | null;
            name: string;
            upload?: components["schemas"]["VideoUpload"] | null;
            video?: components["schemas"]["ExerciseVideo"] | null;
        };
        /** @description Changes to an exercise; fields left out stay as they are. */
        ExerciseChanges: {
            /** @description Hides it from the library. Old workouts keep showing it. */
            archived?: boolean | null;
            /** @description An empty string clears the group. */
            muscle_group?: string | null;
            name?: string | null;
        };
        ExerciseVideo: {
            /** @description HLS playlist. iOS plays it natively; elsewhere the app uses hls.js. */
            hls_url: string;
            /** Format: int32 */
            length_secs?: number | null;
            thumbnail_url: string;
        };
        FinishWorkout: {
            comment?: string;
            /**
             * Format: int32
             * @description From the first ticked set to finishing, as the phone measured it.
             */
            duration_min?: number | null;
            effort: components["schemas"]["Effort"];
        };
        Health: {
            database: boolean;
            status: string;
        };
        ImportParseRequest: {
            /** @description An old plan copied from a Telegram message. */
            text: string;
        };
        ImportPreview: {
            exercises: components["schemas"]["ImportedExercise"][];
            /** @description Lines that could not be read, to show the coach. */
            unparsed: string[];
        };
        ImportedExercise: {
            /**
             * Format: uuid
             * @description The library exercise with this name or alias; `null` means it will be added.
             */
            exercise_id?: string | null;
            /** @description The name as written in the plan. */
            name: string;
            note?: string | null;
            per_side_label?: string | null;
            sets: components["schemas"]["ImportedSet"][];
        };
        ImportedSet: {
            /**
             * Format: double
             * @description `null` for bodyweight.
             */
            kg?: number | null;
            /** Format: int32 */
            reps_max: number;
            /** Format: int32 */
            reps_min: number;
        };
        InviteLink: {
            /** Format: date-time */
            expires_at: string;
            /** @description `https://t.me/<bot>?start=inv_<code>`. Works once. */
            url: string;
        };
        /** @description Who opened the Mini App decides which screens they get. */
        MiniAppSession: {
            coach: components["schemas"]["CoachProfile"];
            /** @enum {string} */
            role: "coach";
            token: string;
        } | {
            client: components["schemas"]["ClientProfile"];
            /** @enum {string} */
            role: "client";
            token: string;
        };
        NewClient: {
            name: string;
        };
        NewExercise: {
            muscle_group?: string | null;
            name: string;
        };
        NewWorkout: {
            /** Format: uuid */
            client_id: string;
            /**
             * Format: uuid
             * @description Start as a copy of this workout (any of the coach's), instead of blank.
             */
            copy_from?: string | null;
            /**
             * Format: date
             * @description For a copy, defaults to a week after the copied workout's date.
             */
            date?: string | null;
        };
        /** @description A logged set from an earlier workout. */
        PastSet: {
            /**
             * Format: double
             * @description `null` for bodyweight.
             */
            kg?: number | null;
            /** Format: int32 */
            reps?: number | null;
        };
        PublishedWorkout: {
            /** @description The bot has told the client; `false` while they have not joined the app. */
            client_notified: boolean;
            workout: components["schemas"]["Workout"];
        };
        Report: {
            comment: string;
            /** Format: int32 */
            duration_min?: number | null;
            effort: components["schemas"]["Effort"];
            /** Format: date-time */
            finished_at: string;
        };
        ReportSummary: {
            effort: components["schemas"]["Effort"];
            /** Format: date-time */
            finished_at: string;
            has_comment: boolean;
            /** @description Dasha has opened it. */
            seen: boolean;
        };
        ResultExercise: {
            /** Format: uuid */
            id: string;
            name: string;
            per_side_label?: string | null;
            sets: components["schemas"]["ResultSet"][];
        };
        ResultSet: {
            /** Format: double */
            actual_kg?: number | null;
            /** Format: int32 */
            actual_reps?: number | null;
            completed: boolean;
            /** @description Ticked with other numbers than planned. */
            differs: boolean;
            /** Format: uuid */
            id: string;
            /** Format: double */
            target_kg?: number | null;
            /** Format: int32 */
            target_reps_max: number;
            /** Format: int32 */
            target_reps_min: number;
        };
        /**
         * @description One set as logged on the phone. Sending it again is harmless, and a write
         *     older than the stored one (it waited offline) is ignored.
         */
        SetResult: {
            /** Format: double */
            actual_kg?: number | null;
            /** Format: int32 */
            actual_reps?: number | null;
            /**
             * Format: date-time
             * @description When the phone recorded this change.
             */
            client_updated_at: string;
            /** @description Ticked ✓. */
            completed: boolean;
        };
        SetTimezone: {
            /** @description IANA name from `Intl.DateTimeFormat().resolvedOptions().timeZone`. */
            timezone: string;
        };
        /** @enum {string} */
        UploadStatus: "uploading" | "processing" | "failed";
        /** @description What the phone needs to upload one video straight to Bunny with tus. */
        UploadTicket: {
            /** @description Bunny's tus endpoint. */
            endpoint: string;
            /**
             * Format: int64
             * @description Unix seconds; send as the `AuthorizationExpire` header.
             */
            expires_at: number;
            /** @description Send as the `LibraryId` header. */
            library_id: string;
            /** @description Send as the `AuthorizationSignature` header. */
            signature: string;
            /** @description Send as the `VideoId` header. */
            video_id: string;
        };
        VideoUpload: {
            /** Format: date-time */
            started_at: string;
            status: components["schemas"]["UploadStatus"];
        };
        WebAppAuthRequest: {
            /** @description `Telegram.WebApp.initData`, exactly as the Mini App received it. */
            init_data: string;
        };
        /** @description A workout as one document: what the builder loads and saves. */
        Workout: {
            /**
             * Format: uuid
             * @description `null` for a template.
             */
            client_id?: string | null;
            /**
             * Format: date
             * @description A calendar date for the client. Needed to publish.
             */
            date?: string | null;
            exercises: components["schemas"]["WorkoutExercise"][];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            published_at?: string | null;
            status: components["schemas"]["WorkoutStatus"];
            title: string;
            /**
             * Format: int32
             * @description Send it back as `If-Match` when saving.
             */
            version: number;
        };
        /**
         * @description The whole workout as the builder has it now. Rows keep their IDs across
         *     saves, so results the client already logged stay attached.
         */
        WorkoutChanges: {
            /** Format: date */
            date?: string | null;
            /** @description In order. */
            exercises: components["schemas"]["WorkoutExerciseChanges"][];
            title: string;
        };
        WorkoutExercise: {
            /** Format: uuid */
            exercise_id: string;
            /** Format: uuid */
            id: string;
            /** @description What the client did the last time this exercise came up ("Минулого разу"). */
            last_time: components["schemas"]["PastSet"][];
            /** @description From the library, for display. */
            name: string;
            note?: string | null;
            /** @description E.g. `на кожну руку`: the targets are per arm or leg. */
            per_side_label?: string | null;
            sets: components["schemas"]["WorkoutSet"][];
            thumbnail_url?: string | null;
        };
        WorkoutExerciseChanges: {
            /** Format: uuid */
            exercise_id: string;
            /**
             * Format: uuid
             * @description A new row gets its ID from the app, so a retried save cannot duplicate it.
             */
            id: string;
            note?: string | null;
            per_side_label?: string | null;
            /** @description In order. */
            sets: components["schemas"]["WorkoutSet"][];
        };
        /** @description Targets next to what the client did, for Dasha's report view. */
        WorkoutResults: {
            /** Format: uuid */
            client_id?: string | null;
            /** Format: date */
            date?: string | null;
            exercises: components["schemas"]["ResultExercise"][];
            /** Format: uuid */
            id: string;
            report?: components["schemas"]["CoachReport"] | null;
            status: components["schemas"]["WorkoutStatus"];
            title: string;
        };
        /** @description One set's target, as Dasha writes it. */
        WorkoutSet: {
            /** Format: uuid */
            id: string;
            /**
             * Format: double
             * @description `null` for bodyweight.
             */
            kg?: number | null;
            /** Format: int32 */
            reps_max: number;
            /**
             * Format: int32
             * @description `8-10` is 8 and 10; a plain `12` is 12 and 12.
             */
            reps_min: number;
        };
        /** @enum {string} */
        WorkoutStatus: "draft" | "published" | "done";
        WorkoutSummary: {
            /** Format: date */
            date?: string | null;
            /**
             * Format: int64
             * @description Ticked sets with other numbers than planned.
             */
            different_count: number;
            /**
             * Format: int64
             * @description Sets the client ticked.
             */
            done_set_count: number;
            /** Format: int64 */
            exercise_count: number;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            published_at?: string | null;
            report?: components["schemas"]["ReportSummary"] | null;
            /** Format: int64 */
            set_count: number;
            status: components["schemas"]["WorkoutStatus"];
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bot_login_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotLoginStart"];
                };
            };
        };
    };
    bot_login_poll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotLoginPollRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotLoginPoll"];
                };
            };
        };
    };
    telegram_webapp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAppAuthRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiniAppSession"];
                };
            };
            /** @description `initData` is invalid or older than a day */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `not_invited`: neither the coach nor an invited client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_clients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachClient"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_client: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewClient"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedClient"];
                };
            };
            /** @description `invalid_name` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_client: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachClient"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reinvite_client: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLink"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_client_workouts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSummary"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_exercises: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_exercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewExercise"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            /** @description `invalid_name` or `invalid_group` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `name_taken`: the library already has it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_exercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exercise id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_exercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exercise id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseChanges"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            /** @description `invalid_name` or `invalid_group` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `name_taken` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_video_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exercise id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `video_not_configured`: no Bunny settings */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    finish_video_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exercise id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    parse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportParseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
            /** @description `text_too_long` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `wrong_role` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_workout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWorkout"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such client, or no such workout to copy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_workout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    save_workout: {
        parameters: {
            query?: never;
            header: {
                /** @description The `version` the changes are based on */
                "If-Match": string;
            };
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutChanges"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"];
                };
            };
            /** @description `version_required`, `invalid_title`, `invalid_text`, `invalid_set`, `too_many_exercises`, `too_many_sets`, `invalid_ids` or `unknown_exercise` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `version_conflict`: reload and apply the changes again */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_workout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    publish_workout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedWorkout"];
                };
            };
            /** @description `template`, `date_required`, `empty_workout` or `exercise_without_sets` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    mark_report_seen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such workout, or no report yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_workout_results: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutResults"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientProfile"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_timezone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTimezone"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `unknown_timezone` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_my_workouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientWorkoutSummary"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    log_set: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Set id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetResult"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_result` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_my_workout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientWorkout"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not theirs, or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    finish_workout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workout id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishWorkout"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_report` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
