/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/bot-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a coach sign-in that the coach confirms in the bot. */
        post: operations["bot_login_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/bot-login/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collects the result of a coach sign-in started with `/auth/bot-login`. */
        post: operations["bot_login_poll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/telegram-webapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mini App sign-in: trades Telegram-signed `initData` for a session token. */
        post: operations["telegram_webapp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All of the coach's clients, newest first. */
        get: operations["list"];
        put?: never;
        /** Adds a client and returns their first invite link. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/clients/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A fresh invite link. The previous unused link stops working.
         * @description For a client who already joined, the new link re-links the profile to whoever
         *     opens it, e.g. after they switched Telegram accounts.
         */
        post: operations["reinvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coach/import/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reads an old Telegram plan and matches it against the library. Saves nothing. */
        post: operations["parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check for the hosting platform. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in client's profile. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stores the phone's timezone so reminders arrive at the client's local time. */
        put: operations["set_timezone"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BotLoginPoll: {
            /** @enum {string} */
            status: "pending";
        } | {
            /** @enum {string} */
            status: "cancelled";
        } | {
            /** @enum {string} */
            status: "expired";
        } | {
            coach: components["schemas"]["CoachProfile"];
            /** @enum {string} */
            status: "approved";
            token: string;
        };
        BotLoginPollRequest: {
            poll_secret: string;
        };
        BotLoginStart: {
            /** @description Opens the bot in Telegram with the login code. */
            bot_url: string;
            /** @description Shown on the page; the bot shows the same digits before the coach confirms. */
            display_code: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Keep in the page; send it to `/auth/bot-login/poll` to collect the token. */
            poll_secret: string;
        };
        ClientProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description IANA timezone reported by the client's phone, e.g. `Europe/Kyiv`. */
            timezone?: string | null;
        };
        ClientSession: {
            client: components["schemas"]["ClientProfile"];
            token: string;
        };
        CoachClient: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description Set while an unused invite exists; it may already have expired.
             */
            invite_expires_at?: string | null;
            /** @description The client opened their invite and is linked to a Telegram account. */
            joined: boolean;
            name: string;
            /** Format: date */
            paid_until?: string | null;
        };
        CoachProfile: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        CreatedClient: {
            client: components["schemas"]["CoachClient"];
            invite: components["schemas"]["InviteLink"];
        };
        ErrorBody: {
            /** @description Machine-readable code, e.g. `unauthorized`, `not_a_client`, `unknown_timezone`. */
            error: string;
        };
        Health: {
            database: boolean;
            status: string;
        };
        ImportParseRequest: {
            /** @description An old plan copied from a Telegram message. */
            text: string;
        };
        ImportPreview: {
            exercises: components["schemas"]["ImportedExercise"][];
            /** @description Lines that could not be read, to show the coach. */
            unparsed: string[];
        };
        ImportedExercise: {
            /**
             * Format: uuid
             * @description The library exercise with this name or alias; `null` means it will be added.
             */
            exercise_id?: string | null;
            /** @description The name as written in the plan. */
            name: string;
            note?: string | null;
            per_side_label?: string | null;
            sets: components["schemas"]["ImportedSet"][];
        };
        ImportedSet: {
            /**
             * Format: double
             * @description `null` for bodyweight.
             */
            kg?: number | null;
            /** Format: int32 */
            reps_max: number;
            /** Format: int32 */
            reps_min: number;
        };
        InviteLink: {
            /** Format: date-time */
            expires_at: string;
            /** @description `https://t.me/<bot>?start=inv_<code>`. Works once. */
            url: string;
        };
        NewClient: {
            name: string;
        };
        SetTimezone: {
            /** @description IANA name from `Intl.DateTimeFormat().resolvedOptions().timeZone`. */
            timezone: string;
        };
        WebAppAuthRequest: {
            /** @description `Telegram.WebApp.initData`, exactly as the Mini App received it. */
            init_data: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bot_login_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotLoginStart"];
                };
            };
        };
    };
    bot_login_poll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotLoginPollRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotLoginPoll"];
                };
            };
        };
    };
    telegram_webapp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAppAuthRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSession"];
                };
            };
            /** @description `initData` is invalid or older than a day */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `not_a_client`: this Telegram user has no invite */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachClient"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewClient"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedClient"];
                };
            };
            /** @description `invalid_name` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reinvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteLink"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    parse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportParseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
            /** @description `text_too_long` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `wrong_role` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientProfile"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_timezone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTimezone"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `unknown_timezone` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
